development:
  server: "http://x.x.x.x:9292/faye"
  secret_token: "secret"
production:
  server: "http://x.x.x.x:9292/faye"
  secret_token: "secret"
test:
  server: "http://x.x.x.x:9292/faye"
  secret_token: "secret"